services:
  # marketplace-app
  marketplace-postgres:
    image: postgres
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
    volumes:
      - ./marketplace/postgres_data:/var/lib/postgresql/data

  # keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm"]
    environment:
       DB_VENDOR: POSTGRESQL
       DB_ADDR: keycloak-postgres
       DB_DATABASE: keycloak
       DB_USER: keycloak
       DB_PASSWORD: password
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import/

    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - ./keycloak/postgres_data:/var/lib/postgresql/data

