create table IF NOT EXISTS order_item (
    quantity integer,
    id bigint generated by default as identity,
    order_id bigint,
    product_id bigint,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    primary key (id)
);
